title: Note-bag
description: все обо всем
author: Валерий Сухих
github: https://github.com/vsuh
about: "быстрее! выше! сильнее! это не про меня.."
#disqus_shortname:
#google_analytics: 
url: "http://helor:3000"
host: "192.168.1.2"
port: 3000
enableTags: true
tagarray: [ diy, 1C, python, js, phones, life ]
tags: [ diy, 1C, python, js, phones, life ]




social:
#  github: vsuh
#  stackoverfow: 
#  linkedin: 
#  instagram: 
#  rss: feed.xml


share:
#  twitter_username:
#  fb_appid:

#urls:
#    - text: About Me
#      url: /about/
#    - text: Телефоны
#      url: /docs/phones/
#    - text: Мир 1С
#      url: /docs/world1c/
#    - text: Jekyll
#      url: /docs/jekyll/




url: "https://vsuh.github.io"
baseurl: ""
paginate: 15
per_page: 15
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

collections:
  project:
    output: true
    permalink: /project/:path/
  books:
    output: true

defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "home"
