lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
######################################################
title: Note-bag
email: vsuh@mail.ru
description: 
baseurl: "" 
url: ""
twitter_username: 
github_username:  vsuh
show_downloads: false

#theme: minima
# не отображаются посты theme: jekyll-theme-leap-day
# нет категорий, папок, тэгов remote_theme: pawamoy/jekyll-readthedocs 
theme: jekyll-theme-midnight
# ?? не выводятя посты theme: jekyll-theme-minimal


